---
version: 2
plan:
  project-key: AJL
  key: DDLTEST
  name: dead-domains-linter - tests
variables:
  dockerContainer: adguard/node-ssh:18.13--2

stages:
  - Test:
      manual: false
      final: false
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            npm install -g pnpm

            pnpm install --ignore-scripts --no-optional

            pnpm run lint
            pnpm run test

            rm -rf node_modules
  final-tasks:
    - clean
  requirements:
    - adg-docker: "true"

branches:
  create: for-pull-request
  delete:
    after-deleted-days: "1"
    after-inactive-days: "5"
  link-to-jira: true

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []
other:
  concurrent-build-plugin: system-default
